config/routes.rb
Equitabletod::Application.routes.draw do
  
  match '/search',  to: 'station_areas#index'
  match '/suggest', to: 'search#suggest'

  resources :station_areas
  resources :dictionary_entries
  root to: 'application#index'
    

end

app/models/dictionary_entry.rb
class DictionaryEntry < ActiveRecord::Base
  attr_accessible :code, :description, :importance, :interpretation, :name, :order, :technical_notes

  scope :by_name, -> (name) { where(name: name) }
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  attr_accessible :mode, :slug

  has_many :transit_lines

  before_save :set_slug

  def set_slug
    self.slug = self.mode.parameterize
  end

  def title
    self.mode.titleize
  end

end

app/models/station_area.rb
class StationArea < ActiveRecord::Base

  has_and_belongs_to_many :transit_lines

  def location
    "#{self.latitude} #{self.longitude}"
  end

  # Basic Search

  scope :by_name,      -> name      { where("station_areas.name ~* ?", name) }
  scope :by_muni_name, -> muni_name { where("station_areas.muni_name ~* ?", muni_name) }
  scope :by_line,      -> by_line   { includes(:transit_lines).where("transit_lines.name ~* ?", by_line) }
  
  scope :by_service, -> service_type {
    includes(:transit_lines).where("transit_lines.service_type ~* ?", service_type) }
  
  # TODO: once database is fixed, attr in quotes will be station_type
  scope :by_station_class, -> station_class { where("station_areas.station_class ~* ?", station_class) }
  scope :by_etod_category, -> etod_category { where("station_areas.etod_type ~* ?", etod_category) }

  # Advanced Search
  def self.advanced_scopes
    [{ name: :by_median_income,          field_name: "ov_hhinc"    },
    { name: :by_far,                    field_name: "ov_far"      },
    { name: :by_vmt,                    field_name: "ov_vmthday"  },
    { name: :by_percent_transit,        field_name: "ov_pcttran"  },
    { name: :by_parking_acres,          field_name: "ov_prkac"    },
    { name: :by_employment10,           field_name: "ov_emp10"    },
    { name: :by_tax_revenue,            field_name: "ex_taxrev"   },
    { name: :by_households10,           field_name: "ov_hh10"     },
    { name: :by_vehicle_perhousehold,   field_name: "ov_vehphh"   },
    { name: :by_transit_commutingmiles, field_name: "ov_trnpcmi"  },
    { name: :by_ghg,                    field_name: "ov_ghg"      },
    { name: :by_development_intensity,  field_name: "ov_intntot"  },
    { name: :by_development_mix,        field_name: "ov_mix"      },
    { name: :by_residential_density,    field_name: "hupac"       },
    { name: :by_employment_density,     field_name: "ov_empden"   },
    { name: :by_establishments,         field_name: "ov_est_10"   },
    { name: :by_assessed_value,         field_name: "ov_aval"     },
    { name: :by_renter_occupied,        field_name: "ov_rentocc"  },
    { name: :by_nocar_households,       field_name: "ov_hhnocar"  },
    { name: :by_education_attainment,   field_name: "ov_ed_att"   },
    { name: :by_walkscore,              field_name: "walkscore"   },
    { name: :by_commercial_pipeline,    field_name: "ov_emppipe"  },
    { name: :by_residential_pipeline,   field_name: "ov_hupipe"   }]
  end

  self.advanced_scopes.each do |s|
    scope(s[:name].to_sym, -> min, max { where("#{s[:field_name]} >= ? AND #{s[:field_name]} <= ?", min, max) })
  end

end

app/models/transit_line.rb
class TransitLine < ActiveRecord::Base
  attr_accessible :name,
                  :service_type
  
  has_and_belongs_to_many :station_areas
  # belongs_to :service_type

  def full_name
    "#{name} #{service_type_title}"
  end

  def service_type_title
    self.service_type.title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
    def index
    	gon.rabl "app/views/search/names.json.rabl", as: "names"
    	gon.rabl "app/views/search/muni_names.json.rabl", as: "muni_names"
    end
  
end

app/controllers/dictionary_entries_controller.rb
class DictionaryEntriesController < ApplicationController
  
  has_scope :by_name

  def index
    @entries = apply_scopes(DictionaryEntry).all
  end

  def show
    @entry = DictionaryEntry.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
  end

  def suggest
    # Add -- stations_classes: StationArea.pluck(:station_class).uniq,
    render json: ({ station_names: StationArea.pluck(:name).uniq,
                    etod_types:    StationArea.pluck(:etod_type).uniq,
                    munis:         StationArea.pluck(:muni_name).uniq.map(&:titleize) })
  end
end

app/controllers/station_areas_controller.rb
class StationAreasController < ApplicationController

  # For all responses in this controller, return the CORS access control headers.
  after_filter :cors_set_access_control_headers
  
  # Basic Search
  has_scope :by_name
  has_scope :by_muni_name
  has_scope :by_station_class
  has_scope :by_line
  has_scope :by_service
  has_scope :by_etod_category

  # Advanced Search
  StationArea.advanced_scopes.each do |s|
    has_scope(s[:name].to_sym, using: [:min, :max], type: :hash)
  end

  def index
    @station_areas = apply_scopes(StationArea).all
  end

  def show
    @station_area = StationArea.find(params[:id])
  end
end

private

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionary_entries_helper.rb
module DictionaryEntriesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/station_areas_helper.rb
module StationAreasHelper
end

app/views/application/index.html.erb
<div id="header-region"></div>
<div id="main-region">
	<div id="home-region"></div>
	<div id="simple-search"></div>
</div>
<div id="footer-region"></div>

<%= javascript_tag do %>
  $(function() {
    Equitabletod.start({
    	names: gon.names.names,
    	muni_names: gon.muni_names.muni_names
	});
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Information Station" %></title>
  <%= include_gon %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <meta property="og:title" content="">
  <meta property="og:type" content="website">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:description" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= javascript_include_tag "application" %>
</head>
<body>
  <%= yield %>
</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5547782-23', 'auto');
  ga('send', 'pageview');
</script>
</html>

app/views/search/search.html.erb
<h1>Search#search</h1>
<p>Find me in app/views/search/search.html.erb</p>

app/views/search/suggest.html.erb
<h1>Search#suggest</h1>
<p>Find me in app/views/search/suggest.html.erb</p>

app/views/station_areas/index.html.erb
<%- model_class = StationArea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:etod_q0car) %></th>
      <th><%= model_class.human_attribute_name(:etod_q25k) %></th>
      <th><%= model_class.human_attribute_name(:etod_qabc) %></th>
      <th><%= model_class.human_attribute_name(:etod_qaff) %></th>
      <th><%= model_class.human_attribute_name(:etod_qdens) %></th>
      <th><%= model_class.human_attribute_name(:etod_qgrav) %></th>
      <th><%= model_class.human_attribute_name(:etod_qrent) %></th>
      <th><%= model_class.human_attribute_name(:etod_qtas) %></th>
      <th><%= model_class.human_attribute_name(:etod_qtci) %></th>
      <th><%= model_class.human_attribute_name(:etod_qwalk) %></th>
      <th><%= model_class.human_attribute_name(:etod_sub1t) %></th>
      <th><%= model_class.human_attribute_name(:etod_sub2o) %></th>
      <th><%= model_class.human_attribute_name(:etod_sub3d) %></th>
      <th><%= model_class.human_attribute_name(:etod_total) %></th>
      <th><%= model_class.human_attribute_name(:etod_type) %></th>
      <th><%= model_class.human_attribute_name(:station_class) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @station_areas.each do |station_area| %>
      <tr>
        <td><%= link_to station_area.id, station_area_path(station_area) %></td>

        <td><%= station_area.location %></td>
        <td><%= station_area.etod_q0car %></td>
        <td><%= station_area.etod_q25k %></td>
        <td><%= station_area.etod_qabc %></td>
        <td><%= station_area.etod_qaff %></td>
        <td><%= station_area.etod_qdens %></td>
        <td><%= station_area.etod_qgrav %></td>
        <td><%= station_area.etod_qrent %></td>
        <td><%= station_area.etod_qtas %></td>
        <td><%= station_area.etod_qtci %></td>
        <td><%= station_area.etod_qwalk %></td>
        <td><%= station_area.etod_sub1t %></td>
        <td><%= station_area.etod_sub2o %></td>
        <td><%= station_area.etod_sub3d %></td>
        <td><%= station_area.etod_total %></td>
        <td><%= station_area.etod_type %></td>
        <td><%= station_area.station_class %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_station_area_path(station_area), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      station_area_path(station_area),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_station_area_path,
            :class => 'btn btn-primary' %>